;METADATA=(Diff=true, UseCommands=true)
[PlayerControl]
CanRotateCamera=true
InputMoveScale_X=1
InputMoveScale_Y=1
ControlVectorEnabled_X=false
ControlVectorEnabled_Y=false
ControlVectorEnabled_Z=true
CameraDistance=400
CameraAngle.Y=-20
CameraAngle.Z=0
CameraAngle.X=0
CameraOffset.Z=0
CameraOffset.Y=0
CameraOffset.X=0

