// Copyright Studio Syndicat 2021. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "AssetTypeCategories.h"
#include "Modules/ModuleInterface.h"
#include "Factories/Factory.h"
#include "Modules/ModuleManager.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "OmegaEditorFactories.h"
#include "UnrealEd.h"
#include "Styling/SlateStyle.h"


#define RegisterDefaultEvent(Class, FuncName) \
(FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, Class::StaticClass(), GET_FUNCTION_NAME_CHECKED(Class, FuncName)))

//class UOmegaEditorFactories;

class FOmegaEditor : public IModuleInterface
{
	public:

TSharedPtr<FSlateStyleSet> StyleSet;

	EAssetTypeCategories::Type OmegaAssetCategory;
	
	/* Called when the module is loaded */
	virtual void StartupModule() override;

	/* Called when the module is unloaded */
	virtual void ShutdownModule() override;
private:
	
};
