// Copyright Studio Syndicat 2021. All Rights Reserved.


#include "Subsystems/Subsystem_GameManager.h"

#include "LuaBlueprintFunctionLibrary.h"
#include "LuaSettings.h"
#include "LuaSubsystem.h"
#include "OmegaSettings.h"
#include "Misc/OmegaGameplayModule.h"
#include "OmegaSettings_Gameplay.h"
#include "OmegaSettings_Global.h"
#include "OmegaSettings_Paths.h"
#include "Engine/GameInstance.h"
#include "Functions/F_File.h"
#include "Misc/OmegaUtils_Macros.h"
#include "Misc/OmegaUtils_Methods.h"
#include "Subsystems/Subsystem_AssetHandler.h"
#include "Subsystems/Subsystem_Mods.h"


UOmegaGameplayModule* UOmegaGameManager::ModuleInit(UOmegaGameplayModule* NewModule)
{
	if(NewModule)
	{
		ActiveModules.Add(NewModule);
		NewModule->Native_Initialize();
		
		UE_LOG(LogTemp, Display, TEXT("%hs_%p"),"Gameplay Module Activated: ", NewModule->GetClass());
		return NewModule;
	}
	return nullptr;
}

void UOmegaGameManager::Initialize(FSubsystemCollectionBase& Colection)
{
	UOmegaSubsystem_AssetHandler* subsys_asset=GEngine->GetEngineSubsystem<UOmegaSubsystem_AssetHandler>();
	UOmegaSettings* settings_omega=GetMutableDefault<UOmegaSettings>();

	
#if !PLATFORM_ANDROID
	subsys_asset->ClearSortedAssets_All();
#endif
	
	
	// Run init Lua code
	//ULuaBlueprintFunctionLibrary::LuaRunString(this,nullptr,OGF_CFG_LUA()->Code_Init.LuaCode);
	OGF_LUA_DOCODE(OGF_CFG_LUA()->Code_Init)
	// --------------------------------------
	// ACTIVATE & REGISTER MODULES
	// --------------------------------------
	
	for(TSubclassOf<UOmegaGameplayModule> TempModule : GetMutableDefault<UOmegaSettings>()->GetGameplayModuleClasses())
	{
		if(TempModule)
		{
			ActivateModuleFromClass(TempModule);
		}
	}
	if(UOmegaSettings_Gameplay* _set=Cast<UOmegaSettings_Gameplay>(GetMutableDefault<UOmegaSettings>()->DefaultSettings_Gameplay.TryLoad()))
	{
		for(auto* c : _set->GetModules())
		{
			if(c)
			{
				UOmegaGameplayModule* new_mod=DuplicateObject(c,GetGameInstance());
				ModuleInit(new_mod);
			}
		}
	}
	
	// --------------------------------------
	// Override File Import
	// --------------------------------------
	
	if (settings_omega->bAutoImportRuntimeAssets)
	{
		if (UOmegaFileManagerSettings* set=settings_omega->GetSettings_File())
		{
			UE_LOG(LogInit, Log, TEXT("======================================================"));
			UE_LOG(LogInit, Log, TEXT("	STARTING RUNTIME FILE IMPORT"));
			UE_LOG(LogInit, Log, TEXT("======================================================"));
			
			for (FString dir_path : OGF_CFG()->RuntimeImport_BaseDirectory)
			{
				UE_LOG(LogInit, Log, TEXT("		📁 IMPORTING DIRECTORY:  %s"), *dir_path);
				for (FString path : OGF_File::ListFilesInDirectory(dir_path,true))
				{
					if (UObject* new_file=set->ImportFile(path))
					{
						UE_LOG(LogInit, Log, TEXT("				✅ IMPORT SUCCESS:  %s"), *path);
						FString New_name=FPaths::GetBaseFilename(path);
						subsys_asset->Register_SortedAsset(new_file,*New_name,true);
					}
					else
					{
						UE_LOG(LogInit, Log, TEXT("				❌ IMPORT FAILED: %s"), *path);
					}
				}
			}	
		}
	}
	
	// --------------------------------------
	// Run auto lua files
	// --------------------------------------
	
	ULuaSettings* settings_ref = GetMutableDefault<ULuaSettings>();
	ULuaSubsystem* lsub=GetGameInstance()->GetSubsystem<ULuaSubsystem>();
	if(settings_ref->bAutorunFiles)
	{
		lsub->RunLocalFile(settings_ref->Autorun_InitFile,false);
	}
	
	for (FString f : settings_ref->Autorun_FilePaths)
	{
		lsub->RunLocalFilesInPath(FPaths::ProjectContentDir()+"/"+OGF_File::PathCorrect(f),true,true);
	}
	

	for(TSoftObjectPtr<ULuaCode> temp_asset: settings_ref->AutorunCodeAssets)
	{
		ULuaBlueprintFunctionLibrary::LuaRunCodeAsset(GetWorld(),ULuaBlueprintFunctionLibrary::GetDefaultLuaState(),temp_asset.LoadSynchronous());
	}
	
	// --------------------------------------
	// Initialize Mods
	// --------------------------------------
	
	
	if(settings_omega->bAutoInitializeMods)
	{
		//while (!GetGameInstance()->GetSubsystem<UOmegaModSubsystem>()) { }
		UOmegaModSubsystem* msub=GetGameInstance()->GetSubsystem<UOmegaModSubsystem>();
		while (!msub->mods_initialized)
		{
			//wait for mod initializtion finish
		}
		msub->Init_Mods(this);
	}
	
	// --------------------------------------
	// await lua init finsh before generating asset
	// --------------------------------------
	
	if (GetMutableDefault<ULuaSettings>()->bAutoGenerateDataAssetFromGlobalTable)
	{
		if (ULuaSubsystem* luaSub= GetWorld()->GetGameInstance()->GetSubsystem<ULuaSubsystem>())
		{
			while (luaSub->b_IsInitialized)
			{
				//wait here until finish
			}
			subsys_asset->GenerateLuaTableDataAssets();
		}
	}
	

	settings_omega->GetGlobalSettings()->OnGame_Begin(GetWorld()->GetGameInstance());
	
}

void UOmegaGameManager::Deinitialize()
{
	UOmegaSettings* _set=GetMutableDefault<UOmegaSettings>();
	_set->GetGlobalSettings()->OnGame_Begin(GetWorld()->GetGameInstance());
	
	for(UOmegaGameplayModule* TempModule : ActiveModules)
	{
		TempModule->Shutdown();
	}
	
	Super::Deinitialize();
}


//############################################################################
// Gameplay Modules
//############################################################################

UOmegaGameplayModule* UOmegaGameManager::ActivateModuleFromClass(const UClass* ModuleClass)
{
	if(ModuleClass)
	{
		for (auto* TempMod : ActiveModules)
		{
			if(TempMod->GetClass()==ModuleClass)
			{
				return TempMod;
			}
		}
	
		UOmegaGameplayModule* NewModule = NewObject<UOmegaGameplayModule>(GetGameInstance(), ModuleClass);
		return ModuleInit(NewModule);
	}
	return nullptr;
}



UOmegaGameplayModule* UOmegaGameManager::GetGameplayModule(TSubclassOf<UOmegaGameplayModule> Module)
{
	for(UOmegaGameplayModule* TempModule : ActiveModules)
	{
		if(TempModule->GetClass()->IsChildOf(Module))
		{
			return TempModule;
		}
	}
	return nullptr;
}

TArray<UOmegaGameplayModule*> UOmegaGameManager::GetGameplayModules()
{
	return ActiveModules;
}

void UOmegaGameManager::FireGlobalEvent(FName Event, UObject* Context)
{
	OnGlobalEvent.Broadcast(Event, Context);
}

void UOmegaGameManager::FireTaggedGlobalEvent(FGameplayTag Event, UObject* Context)
{
	OnTaggedGlobalEvent.Broadcast(Event,Context);
}

void UOmegaGameManager::SetFlagActive(FString Flag, bool bActive)
{
	if(IsFlagActive(Flag) != bActive)
	{
		if(bActive)
		{
			Flags.AddUnique(Flag);
		}
		else
		{
			Flags.Remove(Flag);
		}
		OnFlagStateChange.Broadcast(Flag, bActive);
	}
}

bool UOmegaGameManager::IsFlagActive(FString Flag)
{
	return Flags.Contains(Flag);
}

void UOmegaGameManager::ClearAllFlags()
{
	TArray<FString> LocalFlags = Flags;
	for(FString TempFlag : LocalFlags)
	{
		SetFlagActive(TempFlag, false);	
	}
	Flags.Empty();
}



void UOmegaGameManager::AddGameplayLog(const FString& String, const FString& LogCategory)
{
	FGameplayLogEntry TempEntry;
	TempEntry.Log = String;
	TempEntry.LogCategory = LogCategory;
	LocalLog.Add(TempEntry);
}

void UOmegaGameManager::ClearLog()
{
	LocalLog.Empty();
}

TArray<FString> UOmegaGameManager::GetGameplayLog()
{
	TArray<FString> LocalStrings;
	for(FGameplayLogEntry TempEntry : LocalLog)
	{
		LocalStrings.Add(TempEntry.Log);
	}
	LocalStrings.SetNum(MaxLogEntry);
	return LocalStrings;
}

TArray<FString> UOmegaGameManager::GetGameplayLogOfCategory(const FString& LogCategory)
{TArray<FString> LocalStrings;
	for(FGameplayLogEntry TempEntry : LocalLog)
	{
		if(TempEntry.LogCategory == LogCategory)
		{
			LocalStrings.Add(TempEntry.Log);
		}
	}
	LocalStrings.SetNum(MaxLogEntry);
	return LocalStrings;
	
}

