// Fill out your copyright notice in the Description page of Project Settings.


#include "Subsystems/Subsystem_Engine.h"
#include "Engine/World.h"
#include "Interfaces/I_Common.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "IPlatformFilePak.h"
#include "LuaBlueprintFunctionLibrary.h"
#include "LuaInterface.h"
#include "LuaSettings.h"
#include "OmegaSettings.h"
#include "OmegaGameManager.h"
#include "OmegaGameplayConfig.h"
#include "Functions/F_Common.h"
#include "HAL/PlatformFilemanager.h"
#include "Misc/OmegaUtils_Methods.h"
#include "Misc/Paths.h"
#include "Misc/PackageName.h"


void UOmegaSubsystem_Engine::OnGameInitialized()
{
	//cass class paths from config
	cached_ClassPaths.Empty();
	for (TSoftObjectPtr<UOmegaGameplayConfig> cfg : OGF_CFG()->Imported_GameplaySettings)
	{
		if (UOmegaGameplayConfig* _cfg=cfg.LoadSynchronous())
		{
			cached_ClassPaths.Append(_cfg->ClassPaths);
		}
	}
}

void UOmegaSubsystem_Engine::GenerateLuaTableDataAssets()
{
	TArray<UPrimaryDataAsset*> _list;
	TArray<FLuaValue> _tableKeys;
	
	TMap<FName,TSubclassOf<UPrimaryDataAsset>> _TableDataAssets;
	
	for (auto _preset : GetMutableDefault<ULuaSettings>()->Settings_Presets)
	{
		if (ULuaSettings_Preset* p=_preset.LoadSynchronous())
		{
			TArray<FName> _TempKeys;
			p->AutoGeneratedDataAssets.GetKeys(_TempKeys);
			for (FName n : _TempKeys)
			{
				_TableDataAssets.Add(n,p->AutoGeneratedDataAssets[n]);
			}
		}
	}
	
	TArray<FName> _TempKeys;
	_TableDataAssets.GetKeys(_TempKeys);
	
	for (FName n : _TempKeys)
	{
		//get Lua table from found DA key
		FLuaValue current_table=ULuaBlueprintFunctionLibrary::LuaGetGlobal(this,nullptr,n.ToString());
		if (!current_table.IsNil())
		{
			if (TSubclassOf<UPrimaryDataAsset> daC = _TableDataAssets[n])
			{
				//iterate though each table key to generate data assets
				for (FLuaValue gKey : ULuaBlueprintFunctionLibrary::LuaTableGetKeys(current_table))
				{
					UObject* _target_object;
					//if asset key already exists, just updated it
					bool outcome;
					if (UObject* _tempObject=UOmegaGameFrameworkBPLibrary::GetAsset_FromPath(gKey.ToString(),daC,outcome))
					{
						_target_object=_tempObject;
					}
					//else generate from lua table if new.
					else
					{
						FString _ObjectName=n.ToString()+"."+gKey.ToString();
						_target_object=NewObject<UObject>(this,daC,*_ObjectName);
						//Register_SortedAsset(_target_object,gKey.ToString(),true);
					}
					
					//finish up by setting lua values;
					if (_target_object && _target_object->GetClass()->ImplementsInterface(ULuaInterface::StaticClass()))
					{
						FLuaValue _inVal=current_table.GetField(gKey.ToString());
						if (UOmegaGameManager* set=GetMutableDefault<UOmegaSettings>()->GetGameCore())
						{
							set->Lua_OnObjectGeneration(_target_object,gKey,_inVal);
						}
						ILuaInterface::Execute_SetKey(_target_object,gKey);
						ILuaInterface::Execute_SetValue(_target_object,_inVal,"");
					}
				}
			}
		}
	}
}

TArray<UObject*> UOmegaFunctions_Engine::SortedAsset_GetAll()
{
	TArray<UObject*> out;
	if (UOmegaSubsystem_Engine* e=OGF_Subsystems::oEngine())
	{
		TArray<FString> AssetLabeles;
		e->SortedAssets.GetKeys(AssetLabeles);
		for (FString AssetLabel : AssetLabeles)
		{
			out.Add(e->SortedAssets[AssetLabel]);
		}
	}
	return out;
}

UObject* UOmegaFunctions_Engine::SortedAsset_Get(FString AssetLabel)
{
	if (UOmegaSubsystem_Engine* e=OGF_Subsystems::oEngine())
	{
		if(e->SortedAssets.Contains(AssetLabel))
		{
			return e->SortedAssets[AssetLabel];
		}
	}
	return nullptr;
}

bool UOmegaFunctions_Engine::SortedAsset_Set(UObject* Asset, FString AssetLabel, bool bOverwrite)
{
	if (UOmegaSubsystem_Engine* e=OGF_Subsystems::oEngine())
	{
		if(Asset && (!e->SortedAssets.Contains(AssetLabel) || bOverwrite))
		{
			e->SortedAssets.Add(AssetLabel,Asset);
			return true;
		}
	}
	return false;
}
