// Fill out your copyright notice in the Description page of Project Settings.


#include "Subsystems/Subsystem_Engine.h"
#include "Engine/World.h"
#include "Interfaces/I_Common.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "IPlatformFilePak.h"
#include "LuaBlueprintFunctionLibrary.h"
#include "LuaInterface.h"
#include "LuaSettings.h"
#include "OmegaSettings.h"
#include "OmegaGameManager.h"
#include "OmegaGameplayConfig.h"
#include "OmegaSettings_Assets.h"
#include "Functions/F_Common.h"
#include "HAL/PlatformFilemanager.h"
#include "Misc/OmegaUtils_Methods.h"
#include "Misc/Paths.h"
#include "Misc/PackageName.h"
#include "PhysicsEngine/PhysicsSettings.h"


void UOmegaSubsystem_Engine::Initialize(FSubsystemCollectionBase& Collection)
{
	Super::Initialize(Collection);
	
	LoadDevConfig();
	
	
	
	TArray<FName> default_surfaces;
	default_surfaces.Add("Grass");
	default_surfaces.Add("Sand");
	default_surfaces.Add("Snow");
	default_surfaces.Add("Ice");
	default_surfaces.Add("Dirt");
	default_surfaces.Add("Mud");
	default_surfaces.Add("Water");
	default_surfaces.Add("Metal");
	default_surfaces.Add("MetalGrate");
	
	
	uint8 i_surfaceIndex=1;
	for (FName default_surface : default_surfaces)
	{
		
		i_surfaceIndex+=1;
		if (GetMutableDefault<UPhysicsSettings>()->PhysicalSurfaces.IsValidIndex(i_surfaceIndex))
		{
			FPhysicalSurfaceName _nam;
			_nam.Name=default_surface;
			//_nam.Type=i_surfaceIndex;
			GetMutableDefault<UPhysicsSettings>()->PhysicalSurfaces[i_surfaceIndex]=_nam;
		}
	}
	
}

void UOmegaSubsystem_Engine::LoadDevConfig()
{
	FString _path=FPaths::ProjectDir()+"/devconfig.lua";
	if (FPaths::FileExists(_path))
	{
		FLuaValue loadedVal=ULuaBlueprintFunctionLibrary::LuaRunNonContentFile(this,nullptr,_path,true);
		if (!loadedVal.IsNil())
		{
			devconfig_table=loadedVal;
			OGF_Log::LogInfo("DEV CONFIG: Sucessfully loaded");
			keys_spawnables.Empty();
			TArray<FLuaValue> spawnKeys= ULuaBlueprintFunctionLibrary::LuaTableGetKeys(devconfig_table.GetField("spawnables"));
			for (FLuaValue key : spawnKeys)
			{
				keys_spawnables.Add(*key.ToString());
			}
		}
		else
		{
			OGF_Log::Warning("DEV CONFIG: File found, but failed to load table");
		}
	}
	else
	{
		OGF_Log::Warning("DEV CONFIG: File does not exist: "+_path);
	}
}

FLuaValue UOmegaSubsystem_Engine::Spawnable_GetData(FName key)
{
	return devconfig_table.GetField("spawnables").GetField(key.ToString());
}

void UOmegaSubsystem_Engine::OnGameInitialized()
{
	//cass class paths from config
	cached_ClassPaths.Empty();
	for (TSoftObjectPtr<UOmegaGameplayConfig> cfg : OGF_CFG()->Imported_GameplaySettings)
	{
		if (UOmegaGameplayConfig* _cfg=cfg.LoadSynchronous())
		{
			cached_ClassPaths.Append(_cfg->ClassPaths);
		}
	}
}

void UOmegaSubsystem_Engine::GenerateLuaTableDataAssets()
{
	TArray<UPrimaryDataAsset*> _list;
	TArray<FLuaValue> _tableKeys;
	
	TMap<FName,TSubclassOf<UPrimaryDataAsset>> _TableDataAssets;
	
	for (auto _preset : GetMutableDefault<ULuaSettings>()->Settings_Presets)
	{
		if (ULuaSettings_Preset* p=_preset.LoadSynchronous())
		{
			TArray<FName> _TempKeys;
			p->AutoGeneratedDataAssets.GetKeys(_TempKeys);
			for (FName n : _TempKeys)
			{
				_TableDataAssets.Add(n,p->AutoGeneratedDataAssets[n]);
			}
		}
	}
	
	TArray<FName> _TempKeys;
	_TableDataAssets.GetKeys(_TempKeys);
	
	for (FName n : _TempKeys)
	{
		//get Lua table from found DA key
		FLuaValue current_table=ULuaBlueprintFunctionLibrary::LuaGetGlobal(this,nullptr,n.ToString());
		if (!current_table.IsNil())
		{
			if (TSubclassOf<UPrimaryDataAsset> daC = _TableDataAssets[n])
			{
				//iterate though each table key to generate data assets
				for (FLuaValue gKey : ULuaBlueprintFunctionLibrary::LuaTableGetKeys(current_table))
				{
					UObject* _target_object;
					//if asset key already exists, just updated it
					bool outcome;
					if (UObject* _tempObject=UOmegaGameFrameworkBPLibrary::GetAsset_FromPath(gKey.ToString(),daC,outcome))
					{
						_target_object=_tempObject;
					}
					//else generate from lua table if new.
					else
					{
						FString _ObjectName=n.ToString()+"."+gKey.ToString();
						_target_object=NewObject<UObject>(this,daC,*_ObjectName);
						//Register_SortedAsset(_target_object,gKey.ToString(),true);
					}
					
					//finish up by setting lua values;
					if (_target_object && _target_object->GetClass()->ImplementsInterface(ULuaInterface::StaticClass()))
					{
						FLuaValue _inVal=current_table.GetField(gKey.ToString());
						if (UOmegaGameManager* set=GetMutableDefault<UOmegaSettings>()->GetGameCore())
						{
							set->Lua_OnObjectGeneration(_target_object,gKey,_inVal);
						}
						ILuaInterface::Execute_SetKey(_target_object,gKey);
						ILuaInterface::Execute_SetValue(_target_object,_inVal,"");
					}
				}
			}
		}
	}
}

TArray<UObject*> UOmegaFunctions_Engine::SortedAsset_GetAll()
{
	TArray<UObject*> out;
	if (UOmegaSubsystem_Engine* e=OGF_Subsystems::oEngine())
	{
		TArray<FString> AssetLabeles;
		e->SortedAssets.GetKeys(AssetLabeles);
		for (FString AssetLabel : AssetLabeles)
		{
			out.Add(e->SortedAssets[AssetLabel]);
		}
	}
	return out;
}

UObject* UOmegaFunctions_Engine::SortedAsset_Get(FString AssetLabel)
{
	if (UOmegaSubsystem_Engine* e=OGF_Subsystems::oEngine())
	{
		if(e->SortedAssets.Contains(AssetLabel))
		{
			return e->SortedAssets[AssetLabel];
		}
	}
	return nullptr;
}

bool UOmegaFunctions_Engine::SortedAsset_Set(UObject* Asset, FString AssetLabel, bool bOverwrite)
{
	if (UOmegaSubsystem_Engine* e=OGF_Subsystems::oEngine())
	{
		if(Asset && (!e->SortedAssets.Contains(AssetLabel) || bOverwrite))
		{
			e->SortedAssets.Add(AssetLabel,Asset);
			return true;
		}
	}
	return false;
}
