
#pragma once

#include "CoreMinimal.h"
#include "LuaState.h"
#include "Engine/DeveloperSettings.h"
#include "UObject/SoftObjectPath.h"
#include "LuaSettings.generated.h"

class ULuaObject;

UCLASS()
class LUAMACHINE_API ULuaSettings_Preset : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	
	UPROPERTY(EditAnywhere, Category = "Default")
	TMap<FName,TSubclassOf<UPrimaryDataAsset>> AutoGeneratedDataAssets;
	
	
	UPROPERTY(EditAnywhere, Category = "Default")
	TArray<FString> Autorun_ContentPaths;
	
};


UCLASS(config = Game, defaultconfig, meta = (DisplayName = "Omega: Lua"))
class LUAMACHINE_API ULuaSettings : public UDeveloperSettings
{
	GENERATED_UCLASS_BODY()

public:
	
	TArray<ULuaSettings_Preset*> GetSettingsPresets();
	
	UPROPERTY(EditAnywhere, config, Category = "Default")
	TArray<TSoftObjectPtr<ULuaSettings_Preset>> Settings_Presets;
	UPROPERTY(EditAnywhere, config, Category = "Default", meta = (MetaClass = "LuaState"))
	TSoftClassPtr<ULuaState> DefaultState;
	UPROPERTY(EditAnywhere, config, Category = "Default", meta = (MetaClass = "LuaState"))
	TSoftClassPtr<ULuaObject> DefaultObject;
	UPROPERTY(EditAnywhere, config, Category = "Default")
	bool bAutorunFiles=false;
	UPROPERTY(EditAnywhere, config, Category = "Default")
	bool bAutoGenerateDataAssetFromGlobalTable;
	
	UPROPERTY(EditAnywhere, config, Category = "Default",DisplayName="Autorun - Root Path")
	FString Autorun_ContentPath="Lua";
	UPROPERTY(EditAnywhere, config, Category = "Default",DisplayName="Autorun - Init .lua File")
	FString Autorun_InitFile="main";
	UPROPERTY(EditAnywhere, config, Category = "Default",DisplayName="Autorun - Subpaths")
	TArray<FString> Autorun_FilePaths;
	
	UPROPERTY(EditAnywhere, config, Category = "Default")
	TArray<TSoftObjectPtr<ULuaCode>> AutorunCodeAssets;
	UPROPERTY(EditAnywhere, config, Category = "Save")
	FString GameSave_Table=TEXT("_S");
	UPROPERTY(EditAnywhere, config, Category = "Save")
	FString GlobalSave_Table=TEXT("_SG");
	
	UPROPERTY(EditAnywhere, config, Category = "Field")
	FString FieldKey_Metatags=TEXT("metatags");
	UPROPERTY(EditAnywhere, config, Category = "Field")
	FString FieldKey_CustomLists=TEXT("traits");
	
	UPROPERTY(EditAnywhere, config, Category = "Code")
	FOmegaLuaCode Code_Init;
};

