
#pragma once

#include "CoreMinimal.h"
#include "LuaState.h"
#include "Engine/DeveloperSettings.h"
#include "UObject/SoftObjectPath.h"
#include "LuaSettings.generated.h"

class ULuaObject;

UCLASS()
class LUAMACHINE_API ULuaSettings_Preset : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	
	UPROPERTY(EditAnywhere, Category = "Default")
	TMap<FName,TSubclassOf<UPrimaryDataAsset>> AutoGeneratedDataAssets;
	
	
	UPROPERTY(EditAnywhere, Category = "Default")
	TArray<FString> Autorun_ContentPaths;
	
};


UCLASS(config = Game, defaultconfig, meta = (DisplayName = "Omega: Lua"))
class LUAMACHINE_API ULuaSettings : public UDeveloperSettings
{
	GENERATED_UCLASS_BODY()

public:
	
	TArray<ULuaSettings_Preset*> GetSettingsPresets();
	
	UPROPERTY(EditAnywhere, config, Category = "Default")
	TArray<TSoftObjectPtr<ULuaSettings_Preset>> Settings_Presets;
	UPROPERTY(EditAnywhere, config, Category = "Default")
	TSoftClassPtr<ULuaState> DefaultState;
	UPROPERTY(EditAnywhere, config, Category = "Default")
	TSoftClassPtr<ULuaObject> DefaultObject;
	UPROPERTY(EditAnywhere, config, Category = "Flags")
	bool bAutorunFiles=false;
	UPROPERTY(EditAnywhere, config, Category = "Flags")
	bool bAutoGenerateDataAssetFromGlobalTable;
	//When using "Property Access" functions, will attempt to first get the field from the object's Lua Valie
	UPROPERTY(EditAnywhere, config, Category = "Flags")
	bool bPropertyAccessFromObjectLuaValue=true;
	//Whether to enable getting lua metadata from an object via it's "Metakey" (Metakey = ObjectClassName + "." + ObjectName)
	UPROPERTY(EditAnywhere, config, Category = "Flags")
	bool bUseLuaObjectMetadata=true;
	//Whether to autobind any found UOmegaGlobalScript or UOmegaGlobalCondition classes as callable lua functions
	UPROPERTY(EditAnywhere, config, Category = "Flags")
	bool bAutobindGlobalScriptsAsFunctions=true;
	
	UPROPERTY(EditAnywhere, config, Category = "Autorun",DisplayName="Autorun - Root Path")
	FString Autorun_ContentPath="Lua";
	UPROPERTY(EditAnywhere, config, Category = "Autorun",DisplayName="Autorun - Init .lua File")
	FString Autorun_InitFile="main";
	UPROPERTY(EditAnywhere, config, Category = "Autorun",DisplayName="Autorun - Subpaths")
	TArray<FString> Autorun_FilePaths;
	
	UPROPERTY(EditAnywhere, config, Category = "Default")
	TArray<TSoftObjectPtr<ULuaCode>> AutorunCodeAssets;
	UPROPERTY(EditAnywhere, config, Category = "Default")
	TArray<FString> GlobalScriptBindPaths;
	UPROPERTY(EditAnywhere, config, Category = "Save")
	FString GameSave_Table=TEXT("_S");
	UPROPERTY(EditAnywhere, config, Category = "Save")
	FString GlobalSave_Table=TEXT("_SG");
	
	UPROPERTY(EditAnywhere, config, Category = "Level")
	bool Level_AutoloadLuaTable=true;
	UPROPERTY(EditAnywhere, config, Category = "Level")
	FString Level_GlobalKey=TEXT("_LEVEL");
	
	// prefix for getting an objects meta key. can make a subtable. 
	// E.G. prefix on "Glob." on an object "wpn_sword_1" of class "DA_Weapon_C" would be "Glob.DA_Weapon.wpn_sword_1"
	UPROPERTY(EditAnywhere, config, Category = "Field")
	FString Object_MetakeyPrefex="";
	UPROPERTY()
	FString FieldKey_Metatags=TEXT("metatags");
	UPROPERTY(EditAnywhere, config, Category = "Field")
	FString FieldKey_CustomLists=TEXT("traits");
	
	UPROPERTY(EditAnywhere, config, Category = "Code")
	FOmegaLuaCode Code_Init;
};



